set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" add all your plugins here (note older versions of Vundle
" used Bundle instead of Plugin)

" ...

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" Encoding
set encoding=utf-8

" Syntax
" Plugin 'vim-syntastic/syntastic'
Plugin 'nvie/vim-flake8'
" let python_highlight_all=1
syntax on

" File browsing
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree

" Searching
Plugin 'kien/ctrlp.vim'

" Set apperiance
set nu
set mouse=a
set clipboard+=unnamed
colorscheme termschool

" Git indentation
Plugin 'tpope/vim-fugitive'

" Powerline
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}

" YouCompleteMe
Bundle 'Valloric/YouCompleteMe'
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>

" backspace
set backspace=indent,eol,start  " more powerful backspacing

" run python3
nnoremap <buffer> <F9> :exec 'w !python3' shellescape(@%, 1)<cr>

" powerline
set  rtp+=/usr/local/lib/python3.7/site-packages/powerline/bindings/vim/
set laststatus=2
set t_Co=256

" enforce purity
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> :bp<CR>
nnoremap <right> :bn<CR>
